language: java
jdk:
- oraclejdk8
script: mvn clean verify
notifications:
  slack:
    secure: V1ualh5XPvBZt1p7I06kVwzC4EsXUK45friM0iK5YDOp0uKthMYEneufEJz0qSITFANdwlyXV9tpUvbuINwcgVcVnhwB4bwMQ7tQhfQH/OWb/2ac9r09Op4+IT2Oqp7Ogwz810i0MmUY0r1KVybM4lQ9mtNZLhdEKR3H9sB9YhiH7I4Yncej5kLGhxt2XxAB00ttozCwC+oViHDq68JSJ2Lwo/EqU60GcVSJK/ILIJ+uuydrCEL1dePH4ZtcSjlPkUdl3oNM3v+FpBxInn74KANsKN0LC8egdNVpGvzlDeIdL8QCBUgaNxYImAKki1dh/X1Nm7/0Mtezv0QLluKYkTbO9vKYM/SHe1e87zNCVCXzAqp9W2LcmuibhyDdL8iBGiiINK3VXPmN6zthM7/PUyiH9YhuEE7IWb4RU4tJhn8X178+MZ+gbJSTXCfmYgLJdWutVDtKiY4Ri8H8CoqofrOFFHbuKZ9s2eF358I1OQLQnJY1qWaUF73w57C5+HuURa/rZV1sfXM0D4D+4MhExkc0SVeuunOfTynpKN0mkc1vbs9jh6m30ioAw0HhjrEgPUFTnQcvdS2gBGPvcLOQPvgUqAvUzKgZJ1tzMAMoeFX97vCq8OrqHJN3ads7rodHFV6vxa0A3m/2ZFRVsBH2gMiVuXN3VSSyY1sSTbFZIC4=
